### ISSUE TITLE
Consul-snapshot doesn't close connections when agent is running with ui option

### ISSUE THREAD

**Issue by marcoamorales** [pshima/consul-snapshot#17] opened 2016-12-05 21:10 UTC
Hello,

I've found a problem when running consul-snapshot on the same server that is running a consul agent with -ui option.

From what I can tell, if I'm using the -ui option, consul-snapshot doesn't close the connections it creates with the local agent. The connection count will keep growing until the server is no longer able to create more connections.

Shortend output:
```
# netstat -plant | grep 8500 | grep consul-snap
tcp        0      0 127.0.0.1:39110         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:39690         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:38900         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:40111         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:38768         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:39883         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:39157         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:39722         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:39998         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:38577         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:38911         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:39594         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:39055         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:39449         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:39033         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:39627         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:39868         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
...
tcp        0      0 127.0.0.1:38603         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:38669         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:39982         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:38567         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:38646         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:39579         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:40064         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:40192         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:38591         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:40030         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:38977         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:39461         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:38490         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:39787         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:40176         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:39489         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:39290         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
tcp        0      0 127.0.0.1:39819         127.0.0.1:8500          ESTABLISHED 4004/consul-snapsho
```

**Comment by pshima** [comment] 2016-12-05 21:34
Hi @marcoamorales this sounds like a bug, thanks for your report.  As I have time I will try and reproduce this.

**Comment by kiwivogel** [comment] 2017-02-08 08:42
I have a rather similar issue, only in this case consul-snapshot is not running on one of the master nodes. Massive number of connections and corresponding memory usage.

**Comment by kiwivogel** [comment] 2017-02-08 10:14
I did some more digging. This seems healtcheck related. We were polling the /health endpoint with marathon and are also doing healtchecks with consul. Lowering the HC interval decreases the memory/connection growth. Looks like there's an issue with the connection recycling then I guess.

**Comment by sebamontini** [comment] 2017-08-11 13:23
same issue here, any update on this?

**Comment by pshima** [comment] 2017-08-14 18:45
I think this may be part of the key to what is happening: https://github.com/hashicorp/consul/blob/master/api/api.go#L261

**Comment by pshima** [comment] 2017-08-14 18:47
https://github.com/pshima/consul-snapshot/commit/d0b42784764f63100c89b75ff1bae2d65ec23a83

**Comment by pshima** [comment] 2017-08-14 18:48
Can you build from master and see if the connection issues go away?  If you could help me test this change that would be great as I don't have a long running cluster anymore.

**Comment by pshima** [comment] 2017-08-17 19:29
Dropped in the new 2.3.0 release.  Going to close this but if its still happening please reopen.

**Closed by pshima** 2017-08-17 19:29 UTC

**Comment by kiwivogel** [comment] 2017-08-31 12:05
Rolling out 2.3 to production today, thanks for looking into it 👍
